# -*- coding: utf-8 -*-
"""mp3_player.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNmyp6KhI5lv69P2JF_8EI0lHlh01bbr
"""

import os
import pygame
import tkinter as tk
from tkinter import filedialog

class MP3Player:
    def __init__(self, root):
        self.root = root
        self.root.title("MP3 Player")
        self.playlist = []
        self.current_track = 0

        # Initialize pygame for audio playback
        pygame.init()
        pygame.mixer.init()

        # Create GUI elements
        self.create_widgets()

    def create_widgets(self):
        # Create playlist box
        self.playlist_box = tk.Listbox(self.root, selectmode=tk.SINGLE)
        self.playlist_box.pack(pady=10)

        # Create control buttons
        control_frame = tk.Frame(self.root)
        control_frame.pack()

        self.play_button = tk.Button(control_frame, text="Play", command=self.play_music)
        self.pause_button = tk.Button(control_frame, text="Pause", command=self.pause_music)
        self.stop_button = tk.Button(control_frame, text="Stop", command=self.stop_music)
        self.add_button = tk.Button(control_frame, text="Add to Playlist", command=self.add_to_playlist)
        self.next_button = tk.Button(control_frame, text="Next", command=self.next_track)
        self.prev_button = tk.Button(control_frame, text="Previous", command=self.prev_track)

        self.play_button.grid(row=0, column=0, padx=10)
        self.pause_button.grid(row=0, column=1, padx=10)
        self.stop_button.grid(row=0, column=2, padx=10)
        self.add_button.grid(row=0, column=3, padx=10)
        self.prev_button.grid(row=0, column=4, padx=10)
        self.next_button.grid(row=0, column=5, padx=10)

    def play_music(self):
        if pygame.mixer.music.get_busy() == 0:
            pygame.mixer.music.load(self.playlist[self.current_track])
            pygame.mixer.music.play()

    def pause_music(self):
        if pygame.mixer.music.get_busy() == 1:
            pygame.mixer.music.pause()

    def stop_music(self):
        pygame.mixer.music.stop()

    def add_to_playlist(self):
        file_path = filedialog.askopenfilename(filetypes=[("MP3 files", "*.mp3")])
        if file_path:
            self.playlist.append(file_path)
            self.playlist_box.insert(tk.END, os.path.basename(file_path))

    def next_track(self):
        self.stop_music()
        self.current_track = (self.current_track + 1) % len(self.playlist)
        self.play_music()

    def prev_track(self):
        self.stop_music()
        self.current_track = (self.current_track - 1) % len(self.playlist)
        self.play_music()

if __name__ == "__main__":
    root = tk.Tk()
    mp3_player = MP3Player(root)
    root.mainloop()